vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       image_file:
           uri_prefix: /images
           upload_destination: '%kernel.project_dir%/public/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
